In [55]:
# Install Packages
# !pip install faiss-cpu
# !pip install sentence-transformers

In [56]:
import pandas as pd

pd.set_option('display.max_colwidth', 100)

In [57]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [58]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [59]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors.shape

(8, 768)

In [60]:
vectors[1]

array([-3.35726626e-02,  9.80517827e-03, -3.25012989e-02,  1.86820682e-02,
        1.77041087e-02, -3.62626798e-02, -3.62390615e-02,  7.10840002e-02,
        2.47629695e-02,  2.63499003e-02, -1.21429213e-03, -1.13375969e-02,
       -1.15269180e-02,  1.43791353e-02, -4.38231714e-02, -2.79518887e-02,
        1.75678674e-02, -4.70073568e-03,  8.76718014e-02,  4.92514460e-04,
       -4.46607918e-02, -3.32106054e-02, -1.42118288e-02,  2.29377002e-02,
       -8.52661300e-03, -2.48498423e-03,  8.57963786e-03,  2.66635362e-02,
        2.85465661e-02, -2.94707865e-02, -4.25882675e-02,  1.92414764e-02,
       -2.21508406e-02, -5.22682890e-02,  9.17420266e-07, -2.53167599e-02,
       -5.45516685e-02,  6.14560694e-02, -1.15587283e-02,  1.64797250e-02,
        6.12057687e-04, -6.41633943e-02, -2.64592376e-02,  2.86634564e-02,
       -7.40527967e-03, -3.89426239e-02, -8.28335760e-04,  1.00291803e-01,
       -6.97320374e-03,  2.48220935e-02,  1.85312703e-02, -5.47105540e-03,
        2.40095444e-02, -

In [61]:
dim = vectors.shape[1]
dim

768

In [62]:
import faiss

index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x7f5c96a0f7b0> >

In [63]:
index.add(vectors)

In [64]:
# search_query="I want to buy a polo t-shirt"
search_query="An apple a day keeps the doctor away"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [65]:
vec

array([ 1.77043453e-02,  7.70549402e-02, -1.25192208e-02, -1.39332772e-03,
        5.92108164e-03, -1.42679242e-02, -4.72583845e-02,  3.91947804e-03,
        4.41601165e-02,  3.09807919e-02,  9.15983394e-02,  2.02603042e-02,
       -2.16004811e-02,  1.33208064e-02, -4.14275825e-02,  4.16394919e-02,
        4.37019095e-02,  6.06423104e-03,  2.21781004e-02, -1.94715727e-02,
       -3.44190001e-02,  3.79219800e-02,  5.27905254e-03,  2.22010873e-02,
       -1.11636585e-02, -2.53350977e-02,  7.79389217e-02,  3.47347334e-02,
        1.20056588e-02, -6.52653575e-02, -4.83941101e-02, -3.03445775e-02,
       -6.99562430e-02, -2.53462084e-02,  1.78119137e-06,  1.50222490e-02,
        2.15192139e-02,  2.21124291e-02, -8.38034227e-02,  3.70955793e-03,
       -2.21118387e-02, -8.53062943e-02,  6.44921034e-04,  1.62598062e-02,
       -1.88165884e-02,  3.99217978e-02, -3.13139223e-02,  2.47449670e-02,
       -7.98756164e-03,  6.11144565e-02, -1.47846378e-02,  4.11186666e-05,
        1.20446868e-02,  

In [66]:
import numpy as np
svec = np.array(vec).reshape(1,-1)
svec.shape

(1, 768)

In [67]:
svec

array([[ 1.77043453e-02,  7.70549402e-02, -1.25192208e-02,
        -1.39332772e-03,  5.92108164e-03, -1.42679242e-02,
        -4.72583845e-02,  3.91947804e-03,  4.41601165e-02,
         3.09807919e-02,  9.15983394e-02,  2.02603042e-02,
        -2.16004811e-02,  1.33208064e-02, -4.14275825e-02,
         4.16394919e-02,  4.37019095e-02,  6.06423104e-03,
         2.21781004e-02, -1.94715727e-02, -3.44190001e-02,
         3.79219800e-02,  5.27905254e-03,  2.22010873e-02,
        -1.11636585e-02, -2.53350977e-02,  7.79389217e-02,
         3.47347334e-02,  1.20056588e-02, -6.52653575e-02,
        -4.83941101e-02, -3.03445775e-02, -6.99562430e-02,
        -2.53462084e-02,  1.78119137e-06,  1.50222490e-02,
         2.15192139e-02,  2.21124291e-02, -8.38034227e-02,
         3.70955793e-03, -2.21118387e-02, -8.53062943e-02,
         6.44921034e-04,  1.62598062e-02, -1.88165884e-02,
         3.99217978e-02, -3.13139223e-02,  2.47449670e-02,
        -7.98756164e-03,  6.11144565e-02, -1.47846378e-0

In [68]:
distances, I = index.search(svec, k=2)

In [69]:
I

array([[1, 0]])

In [70]:
df.loc[I[0]]

text category
1  Fruits, whole grains and vegetables helps control blood pressure   Health
0                     Meditation and yoga can improve mental health   Health

In [71]:
search_query

'An apple a day keeps the doctor away'